apiVersion: 1

datasources:
  - name: Loki
    type: loki
    access: proxy
    uid: loki-notely
    url: http://loki:3100
    jsonData:
      maxLines: 1000
      derivedFields:
        - name: traceID
          matcherRegex: 'trace[id|ID]=([a-fA-F0-9-]+)'
          url: '$${__value.raw}'
    isDefault: true
    editable: false
  - name: Prometheus
    type: prometheus
    access: proxy
    uid: prometheus-notely
    url: http://prometheus:9090
    isDefault: false
    editable: false
