const express = require('express');
const shared = require('@notely/shared');
const configModel = require('../models/configModel');
const fs = require('fs').promises;
const path = require('path');

const router = express.Router();
const logger = shared.logger.child({ module: 'nginx-routes' });
const { asyncHandler } = shared.errors;

/**
 * Write IP whitelist configuration file for nginx
 * POST /api/admin/config/security/write-nginx-config
 *
 * Functionality:
 * 1. Fetch current security config from database (ipWhitelist array)
 * 2. Generate nginx IP whitelist config file content
 * 3. Write file to shared volume (nginx will pick up on restart)
 *
 * Note: This endpoint only writes the config file. Nginx restart must be done
 * separately via the docker-manager service (/api/admin/docker/restart/nginx)
 *
 * Authorization: Admin only (handled by gateway)
 */
router.post(
  '/write-nginx-config',
  asyncHandler(async (req, res) => {
    const startTime = Date.now();
    logger.info('Writing IP whitelist config for nginx', { user: req.user?.email });

    try {
      // 1. Fetch current security configuration
      const securityConfig = await configModel.getSecurityConfig();
      const ipWhitelist = securityConfig.ipWhitelist || [];

      logger.info('Fetched IP whitelist configuration', {
        ipCount: ipWhitelist.length,
        ips: ipWhitelist
      });

      // 2. Generate nginx config file content
      const timestamp = new Date().toISOString();
      let configContent = `# Generated by Notely Admin at ${timestamp}\n`;
      configContent += `# IP Whitelist for Admin Access\n`;
      configContent += `# Format: IP_ADDRESS 1; (1 = allow, default 0 = deny when IPs configured)\n`;

      if (ipWhitelist.length === 0) {
        configContent += `# Empty whitelist - all IPs allowed (default behavior)\n`;
      } else {
        configContent += `default 0;\n`;
        ipWhitelist.forEach(ip => {
          // Validate IP format (basic check)
          if (ip && typeof ip === 'string' && ip.trim()) {
            configContent += `${ip.trim()} 1;\n`;
          }
        });
      }

      logger.debug('Generated nginx config content', {
        contentLength: configContent.length,
        lineCount: configContent.split('\n').length
      });

      // 3. Write config file to shared volume (mounted into nginx container)
      try {
        // Write to the dynamic nginx config directory
        // This directory is bind-mounted from host: ./services/nginx/dynamic
        // Nginx reads from: /etc/nginx/dynamic/ip-whitelist.conf
        const configFilePath = path.resolve('/workspace/nginx-dynamic/ip-whitelist.conf');

        await fs.writeFile(configFilePath, configContent, 'utf8');
        logger.info('Successfully wrote IP whitelist config to shared volume', {
          path: configFilePath,
          ipsConfigured: ipWhitelist.length
        });
      } catch (error) {
        logger.error('Failed to write config file', {
          error: error.message,
          stack: error.stack
        });
        return res.status(500).json({
          success: false,
          error: 'config_write_failed',
          message: 'Failed to write configuration file',
          details: error.message
        });
      }

      // 4. Success response
      const executionTime = Date.now() - startTime;

      logger.info('IP whitelist config written successfully', {
        ipsConfigured: ipWhitelist.length,
        executionTimeMs: executionTime
      });

      res.json({
        success: true,
        message: 'IP whitelist configuration file written successfully. Restart nginx to apply changes.',
        ipsConfigured: ipWhitelist.length,
        ipWhitelist: ipWhitelist,
        executionTimeMs: executionTime
      });

    } catch (error) {
      const executionTime = Date.now() - startTime;
      logger.error('Failed to write IP whitelist config', {
        error: error.message,
        stack: error.stack,
        executionTimeMs: executionTime
      });

      res.status(500).json({
        success: false,
        error: 'write_failed',
        message: 'Failed to write IP whitelist configuration',
        details: error.message
      });
    }
  })
);

module.exports = router;
